package com.databricks.jdbc.api.impl;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.databricks.jdbc.api.internal.IDatabricksStatementInternal;
import com.databricks.jdbc.common.StatementType;
import com.databricks.jdbc.dbclient.impl.common.StatementId;
import com.databricks.jdbc.model.core.StatementStatus;
import com.databricks.sdk.service.sql.StatementState;
import java.sql.SQLException;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Independent verification test for client-side maxRows truncation in DatabricksResultSet.next().
 *
 * <p>Per JDBC spec for Statement.setMaxRows(): "Sets the limit for the maximum number of rows that
 * any ResultSet object generated by this Statement object can contain to the given number. If the
 * limit is exceeded, the excess rows are silently dropped."
 *
 * <p>This test derives its expectations purely from the spec, not from the implementation.
 */
class MaxRowsVerificationTest {

  /**
   * Creates a mock IExecutionResult that returns true from next() for exactly {@code totalRows}
   * calls, then returns false.
   */
  private IExecutionResult createMockResult(int totalRows) throws SQLException {
    IExecutionResult result = mock(IExecutionResult.class);
    AtomicInteger counter = new AtomicInteger(0);
    when(result.next())
        .thenAnswer(
            invocation -> {
              return counter.getAndIncrement() < totalRows;
            });
    when(result.hasNext())
        .thenAnswer(
            invocation -> {
              return counter.get() < totalRows;
            });
    when(result.getRowCount()).thenReturn((long) totalRows);
    when(result.getChunkCount()).thenReturn(1L);
    return result;
  }

  /**
   * Creates a mock parent statement that returns the given maxRows value from getMaxRows().
   */
  private IDatabricksStatementInternal createMockStatement(int maxRows) throws Exception {
    IDatabricksStatementInternal stmt = mock(IDatabricksStatementInternal.class);
    when(stmt.getMaxRows()).thenReturn(maxRows);
    return stmt;
  }

  /**
   * Builds a DatabricksResultSet using the @VisibleForTesting constructor.
   */
  private DatabricksResultSet buildResultSet(
      IDatabricksStatementInternal parentStatement,
      IExecutionResult executionResult)
      throws Exception {
    StatementStatus status = new StatementStatus().setState(StatementState.SUCCEEDED);
    StatementId statementId = new StatementId("test-statement-id");
    DatabricksResultSetMetaData metaData = mock(DatabricksResultSetMetaData.class);
    when(metaData.getChunkCount()).thenReturn(1L);

    return new DatabricksResultSet(
        status,
        statementId,
        StatementType.QUERY,
        parentStatement,
        executionResult,
        metaData,
        /* complexDatatypeSupport= */ false);
  }

  @Test
  @DisplayName("maxRows=5, server returns 100 rows -> only 5 returned")
  void testMaxRows5ServerReturns100() throws Exception {
    IExecutionResult mockResult = createMockResult(100);
    IDatabricksStatementInternal mockStmt = createMockStatement(5);
    DatabricksResultSet rs = buildResultSet(mockStmt, mockResult);

    int count = 0;
    while (rs.next()) {
      count++;
      // Safety: should never exceed maxRows
      assertTrue(count <= 5, "Should not return more than maxRows=5 rows");
    }

    assertEquals(5, count, "Expected exactly 5 rows with maxRows=5");
  }

  @Test
  @DisplayName("maxRows=0 (no limit) -> all rows returned")
  void testMaxRowsZeroNoLimit() throws Exception {
    int serverRows = 42;
    IExecutionResult mockResult = createMockResult(serverRows);
    IDatabricksStatementInternal mockStmt = createMockStatement(0);
    DatabricksResultSet rs = buildResultSet(mockStmt, mockResult);

    int count = 0;
    while (rs.next()) {
      count++;
    }

    assertEquals(serverRows, count, "maxRows=0 should return all rows from the server");
  }

  @Test
  @DisplayName("maxRows=1 -> only 1 row returned")
  void testMaxRows1() throws Exception {
    IExecutionResult mockResult = createMockResult(50);
    IDatabricksStatementInternal mockStmt = createMockStatement(1);
    DatabricksResultSet rs = buildResultSet(mockStmt, mockResult);

    int count = 0;
    while (rs.next()) {
      count++;
    }

    assertEquals(1, count, "Expected exactly 1 row with maxRows=1");
  }

  @Test
  @DisplayName("Empty result set with maxRows set -> returns false immediately")
  void testEmptyResultSetWithMaxRows() throws Exception {
    IExecutionResult mockResult = createMockResult(0);
    IDatabricksStatementInternal mockStmt = createMockStatement(10);
    DatabricksResultSet rs = buildResultSet(mockStmt, mockResult);

    assertFalse(rs.next(), "Empty result set should return false on first next() call");
  }

  @Test
  @DisplayName("maxRows does not affect subsequent next() calls after limit - stays false")
  void testMaxRowsStaysFalseAfterLimit() throws Exception {
    IExecutionResult mockResult = createMockResult(100);
    IDatabricksStatementInternal mockStmt = createMockStatement(3);
    DatabricksResultSet rs = buildResultSet(mockStmt, mockResult);

    // Consume maxRows rows
    for (int i = 0; i < 3; i++) {
      assertTrue(rs.next(), "Should return true for row " + (i + 1));
    }

    // All subsequent calls should return false
    assertFalse(rs.next(), "4th call should return false (maxRows=3)");
    assertFalse(rs.next(), "5th call should still return false");
    assertFalse(rs.next(), "6th call should still return false");
  }

  @Test
  @DisplayName("maxRows larger than actual rows -> all rows returned")
  void testMaxRowsLargerThanActualRows() throws Exception {
    int serverRows = 3;
    IExecutionResult mockResult = createMockResult(serverRows);
    IDatabricksStatementInternal mockStmt = createMockStatement(1000);
    DatabricksResultSet rs = buildResultSet(mockStmt, mockResult);

    int count = 0;
    while (rs.next()) {
      count++;
    }

    assertEquals(
        serverRows, count, "When maxRows > actual rows, all actual rows should be returned");
  }

  @Test
  @DisplayName("maxRows with null parent statement -> behaves as no limit (maxRows=0)")
  void testNullParentStatementDefaultsToNoLimit() throws Exception {
    int serverRows = 25;
    IExecutionResult mockResult = createMockResult(serverRows);

    StatementStatus status = new StatementStatus().setState(StatementState.SUCCEEDED);
    StatementId statementId = new StatementId("test-null-parent");
    DatabricksResultSetMetaData metaData = mock(DatabricksResultSetMetaData.class);
    when(metaData.getChunkCount()).thenReturn(1L);

    DatabricksResultSet rs =
        new DatabricksResultSet(
            status,
            statementId,
            StatementType.QUERY,
            /* parentStatement= */ null,
            mockResult,
            metaData,
            false);

    int count = 0;
    while (rs.next()) {
      count++;
    }

    assertEquals(
        serverRows, count, "Null parent statement should default to no row limit (maxRows=0)");
  }
}
